"""refraction-mode tests: phase (default, correct) vs group (legacy) bending.

The two bitwise regressions compare against a snapshot of the PRE-change rays
stored in ``refraction_snapshots.npz`` (generated by ``_generate_snapshots``
while the old code was still in place)."""
import os
import numpy as np
import pytest
import TsunamiTrace as tt

DT = 5.0
G  = 9.8
R_EARTH = 6_371_000.0
_SNAP = os.path.join(os.path.dirname(__file__), "refraction_snapshots.npz")


def _lat_ramp(n_lon=120, n_lat=120, lon_hw=6.0, lat_hw=4.0,
              d_south=6000.0, d_north=3000.0):
    """Ocean whose depth depends only on latitude, centred on the equator."""
    lon = np.linspace(-lon_hw, lon_hw, n_lon)
    lat = np.linspace(-lat_hw, lat_hw, n_lat)
    frac  = (lat - lat[0]) / (lat[-1] - lat[0])          # 0 south -> 1 north
    dep1d = d_south + (d_north - d_south) * frac          # (n_lat,)
    depth = np.repeat(dep1d[None, :], n_lon, axis=0)      # (n_lon, n_lat)
    return lon, lat, depth


def _omega(local_wavelength, local_depth):
    from TsunamiTrace.raytracing import _resolve_omega
    return _resolve_omega(local_wavelength=local_wavelength, local_depth=local_depth)


def _cp_cg(depth_vals, omega):
    """Phase and group speeds at given depth(s) for a fixed omega."""
    from TsunamiTrace.raytracing import _dispersive_group_speed
    cg, cp = _dispersive_group_speed(np.atleast_2d(np.asarray(depth_vals, float)), omega)
    return cp.ravel(), cg.ravel()


# ── bitwise snapshot machinery (default calls -> runs on pre-change code) ────
def _snapshot_cases():
    lon, lat, depth = _lat_ramp()
    base = dict(lon_arr=lon, lat_arr=lat, depth=depth, dt=DT, max_time=2500.0,
                source_lon=0.0, source_lat=-1.0,
                azimuths_deg=np.array([40.0, 60.0, 90.0, 120.0]))
    return {"nd":   dict(base),
            "disp": dict(base, local_wavelength=30e3, local_depth=5500.0)}


def _generate_snapshots(path=_SNAP):
    out = {}
    for name, kw in _snapshot_cases().items():
        rl, ra, rd = tt.trace_rays(**kw)          # default: pre-change behaviour
        out[f"{name}_lon"], out[f"{name}_lat"], out[f"{name}_dir"] = rl, ra, rd
    np.savez(path, **out)
    return path


def _assert_bitwise(a, b):
    assert a.shape == b.shape
    na, nb = np.isnan(a), np.isnan(b)
    assert np.array_equal(na, nb), "NaN masks differ"
    assert np.array_equal(a[~na], b[~nb]), "finite values differ"


@pytest.mark.skipif(not os.path.exists(_SNAP), reason="snapshot not generated")
def test_nondispersive_bitwise_regression():
    """Default (phase) non-dispersive rays == pre-change rays, bit for bit."""
    snap = np.load(_SNAP)
    rl, ra, rd = tt.trace_rays(**_snapshot_cases()["nd"])
    _assert_bitwise(rl, snap["nd_lon"]); _assert_bitwise(ra, snap["nd_lat"])
    _assert_bitwise(rd, snap["nd_dir"])


@pytest.mark.skipif(not os.path.exists(_SNAP), reason="snapshot not generated")
def test_legacy_group_reproduces_old_dispersive_bitwise():
    """refraction='group' on a dispersive wave == pre-change rays, bit for bit."""
    snap = np.load(_SNAP)
    rl, ra, rd = tt.trace_rays(**_snapshot_cases()["disp"], refraction="group")
    _assert_bitwise(rl, snap["disp_lon"]); _assert_bitwise(ra, snap["disp_lat"])
    _assert_bitwise(rd, snap["disp_dir"])


# ── Task 4.3: the decisive Snell invariant ──────────────────────────────────
def test_snell_invariant_phase_conserves_cp_group_conserves_cg():
    lon, lat, depth = _lat_ramp(lat_hw=4.0, d_south=6000.0, d_north=3000.0)
    om = _omega(30e3, 5500.0)
    kw = dict(lon_arr=lon, lat_arr=lat, depth=depth, dt=DT, max_time=3000.0,
              source_lon=0.0, source_lat=-1.5, azimuths_deg=np.array([55.0]),
              local_wavelength=30e3, local_depth=5500.0)

    def q(refraction):
        rl, ra, rd = tt.trace_rays(**kw, refraction=refraction)
        m = ~np.isnan(rl[0])
        d_ray = np.deg2rad(rd[0, m])
        dep   = np.interp(ra[0, m], lat, depth[0, :])        # lat-only bathymetry
        cp, cg = _cp_cg(dep, om)
        return np.sin(d_ray) / cp, np.sin(d_ray) / cg        # (q_p, q_g)

    def spread(x):
        return (np.nanmax(x) - np.nanmin(x)) / abs(np.nanmean(x))

    qp_ph, qg_ph = q("phase")
    qp_gr, qg_gr = q("group")
    # phase mode conserves sin(i)/c_p; group mode conserves sin(i)/c_g
    assert spread(qp_ph) < 5e-3
    assert spread(qg_gr) < 5e-3
    # and the "wrong" invariant is clearly not conserved in each mode
    assert spread(qp_gr) > 3 * spread(qp_ph)
    assert spread(qg_ph) > 3 * spread(qg_gr)


# ── Task 4.4: long-wave limit -> phase and group agree ──────────────────────
def test_long_wave_phase_and_group_agree():
    lon, lat, depth = _lat_ramp()
    kw = dict(lon_arr=lon, lat_arr=lat, depth=depth, dt=DT, max_time=2500.0,
              source_lon=0.0, source_lat=-1.0, azimuths_deg=np.array([60.0]),
              local_wavelength=300e3, local_depth=5500.0)
    rl_p, ra_p, _ = tt.trace_rays(**kw, refraction="phase")
    rl_g, ra_g, _ = tt.trace_rays(**kw, refraction="group")
    m = ~np.isnan(rl_p[0]) & ~np.isnan(rl_g[0])
    cosl = np.cos(np.deg2rad(ra_p[0, m]))
    seg  = np.hypot(np.diff(rl_p[0, m]) * cosl[:-1], np.diff(ra_p[0, m]))
    arc  = seg.sum()
    dpos = np.hypot((rl_p[0, m] - rl_g[0, m]) * cosl, ra_p[0, m] - ra_g[0, m])
    assert dpos.max() / arc < 1e-3


# ── Task 4.5: position eqs undisturbed -> travel time = range / c_group ──────
def test_uniform_depth_travel_time_matches_group_speed():
    n = 120
    lon = np.linspace(-6, 6, n); lat = np.linspace(-6, 6, n)
    depth = np.full((n, n), 5000.0)
    om = _omega(30e3, 5500.0)
    _, cg = _cp_cg([5000.0], om); cg = cg[0]
    for refr in ("phase", "group"):
        rl, ra, _ = tt.trace_rays(lon, lat, depth, dt=DT, max_time=4000.0,
                                  source_lon=0.0, source_lat=0.0,
                                  azimuths_deg=np.array([90.0]),
                                  local_wavelength=30e3, local_depth=5500.0,
                                  refraction=refr)
        m = ~np.isnan(rl[0])
        rng = R_EARTH * np.deg2rad(np.hypot((rl[0, m]) * np.cos(np.deg2rad(ra[0, m])),
                                            ra[0, m]))          # dist from (0,0)
        idx = np.argmin(np.abs(rng - 300_000.0))
        assert abs(idx * DT - rng[idx] / cg) / (idx * DT) < 0.01


# ── Task 4.6: sign flip in the deepest water ────────────────────────────────
def test_refraction_sign_flip_past_cg_maximum():
    # both depths are past the c_group maximum (h~5730 m for a 30 km wave), so
    # phase and group refraction have opposite sign
    lon, lat, depth = _lat_ramp(lat_hw=3.0, d_south=6200.0, d_north=7200.0)
    kw = dict(lon_arr=lon, lat_arr=lat, depth=depth, dt=DT, max_time=2500.0,
              source_lon=0.0, source_lat=0.0, azimuths_deg=np.array([60.0]),
              local_wavelength=30e3, local_depth=5500.0)

    def ddir(refr):
        _, _, rd = tt.trace_rays(**kw, refraction=refr)
        m = ~np.isnan(rd[0])
        return rd[0, m][-1] - rd[0, m][0]

    dphase, dgroup = ddir("phase"), ddir("group")
    assert abs(dphase) > 1e-3 and abs(dgroup) > 1e-3
    assert np.sign(dphase) != np.sign(dgroup), (dphase, dgroup)
